### PR TITLE
Improve HUD documentation

### PR DESCRIPTION
**Pull request by jadtl**
This documents the parameters of the HUD composables.

### CODE REVIEW

**Review by tamaraaPrs — COMMENTED** [review]
Great documentation! 

You can use this PR to understand why the tests you made in your previous PR run infinitely once on the hand. I am aware that it is probably a merge problem, try to run them locally one by one first. I'll let you know if I find out where it comes from. 

A little tip for comments (but I "chippote" at this point!) You can use brackets like this: `[Player]` in your comments to refer to a class!

Thank you very much for this rigor that you put in your comments, being a big fan of detailed comments (maybe a little too much), I validate! 👍

**Comment by jadtl** [comment]
> You can use this PR to understand why the tests you made in your previous PR run infinitely once on the hand.

The culprit was a test asserting that the `ProfileActivity` shows up on a button click, because unlike the `MapActivity` so far, the `ProfileActivity` uses the database, which is not initialized.

Inheriting the test suite from `PolyPolyTest` neatly does the job since it initializes a mock DB, thanks for providing such a useful helper!

> You can use brackets like this: [Player] in your comments to refer to a class!

I added this to the comments, thanks for the tip! :)

> Thank you very much for this rigor that you put in your comments, being a big fan of detailed comments (maybe a little too much), I validate! 👍

Thanks a lot for the kind words, it means a lot.

**Comment by tamaraaPrs** [comment]
The tests of this part are done locally? They're doing a time out again. I also advise you to merge the main on this branch being very careful because it's been a long time since this PR, the main has changed a lot since, especially in its structure. When we make changes in packages, it happens that by merging the main on your branch, you remove work from others (it happened to several of us).

**Comment by tamaraaPrs** [comment]
And thank you so much for trying to find the problem!

**Comment by jadtl** [comment]
> I also advise you to merge the main on this branch being very careful because it's been a long time since this PR, the main has changed a lot since, especially in its structure.

Thanks for pointing that out, I was careful not to discard others' changes so hopefully everything's fine.

> The tests of this part are done locally? They're doing a time out again.

They are passing locally after my fix but apparently this is unrelated to what's going on with Cirrus. It's a shame that there is no screen recording attached to the [report](https://cirrus-ci.com/task/6529560917835776). I'll look into it tomorrow afternoon. I'll see if there is a way to run the CI environment locally to debug this, otherwise I think I'll have to debug by uncommenting tests progressively and pushing to the CI.

**Review by AmLibra — APPROVED** [review]
Simple and clean refactoring, in line with the new paradygm of GameActivity.

**Pull request closed without merging**
